CREATE SEQUENCE IF NOT EXISTS app_user_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS autor_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS reviewer_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE app_user
(
    id        BIGINT       NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname  VARCHAR(255) NOT NULL,
    username  VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    role      VARCHAR(255),
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE article
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    article_status VARCHAR(255),
    title          TEXT                                    NOT NULL,
    content        TEXT                                    NOT NULL,
    journal_id     BIGINT,
    autor_id       BIGINT,
    CONSTRAINT pk_article PRIMARY KEY (id)
);

CREATE TABLE autor
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_autor PRIMARY KEY (id)
);

CREATE TABLE journal
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT                                    NOT NULL,
    CONSTRAINT pk_journal PRIMARY KEY (id)
);

CREATE TABLE review
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    critique_state VARCHAR(255),
    title          TEXT                                    NOT NULL,
    rating         DOUBLE PRECISION,
    review_text    TEXT                                    NOT NULL,
    article_id     BIGINT,
    reviewer_id    BIGINT,
    CONSTRAINT pk_review PRIMARY KEY (id)
);

CREATE TABLE reviewer
(
    id            BIGINT           NOT NULL,
    review_rating DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_reviewer PRIMARY KEY (id)
);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_email UNIQUE (email);

ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_username UNIQUE (username);

ALTER TABLE article
    ADD CONSTRAINT FK_ARTICLE_ON_AUTOR FOREIGN KEY (autor_id) REFERENCES autor (id);

ALTER TABLE article
    ADD CONSTRAINT FK_ARTICLE_ON_JOURNAL FOREIGN KEY (journal_id) REFERENCES journal (id);

ALTER TABLE autor
    ADD CONSTRAINT FK_AUTOR_ON_ID FOREIGN KEY (id) REFERENCES app_user (id);

ALTER TABLE reviewer
    ADD CONSTRAINT FK_REVIEWER_ON_ID FOREIGN KEY (id) REFERENCES app_user (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_ARTICLE FOREIGN KEY (article_id) REFERENCES article (id);

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_REVIEWER FOREIGN KEY (reviewer_id) REFERENCES reviewer (id);